services:
  postgres:
    container_name: webcrawler-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web_crawler
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data

  server:
    container_name: webcrawler-server
    build: server
    env_file: ./server/.env.docker
    ports:
      - 4000:4000
    depends_on:
      - postgres

  mcp:
    container_name: webcrawler-mcp
    build:
      context: .
      dockerfile: ./mcp/Dockerfile
    ports:
      - 3001:3001
    network_mode: host
    depends_on:
      - server

  # Development

  pgadmin:
    container_name: webcrawler-dev-pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@admin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - 5050:80
    depends_on:
      - postgres

  inspector:
    container_name: webcrawler-dev-inspector
    image: node:latest
    command: ["npx", "@modelcontextprotocol/inspector"]
    ports:
      - 6274:6274
    network_mode: host
    depends_on:
      - mcp

  studio:
    container_name: webcrawler-dev-studio
    image: denoland/deno:latest
    working_dir: /app
    command: ["deno", "run", "-A", "npm:prisma", "studio", "--browser", "none"]
    env_file: ./server/.env.docker
    ports:
      - 5555:5555
    volumes:
      - ./server:/app
    depends_on:
      - postgres
