services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web_crawler
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@admin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - 5050:80
  mcp:
    build:
      context: .
      dockerfile: mcp/Dockerfile
    ports:
      - 3001:3001
    network_mode: host
  inspector:
    image: node:latest
    command: ["npx", "@modelcontextprotocol/inspector"]
    ports:
      - 6274:6274
    network_mode: host
#   mcp2:
#     build:
#       context: mcp2
#     ports:
#       - 3001:3001
# networks:
#   default:
#     enable_ipv6: true
#     driver_opts:
#       com.docker.network.enable_ipv6: "true"
